### ISSUE TITLE
Node.js 6 Koa2 error

### ISSUE THREAD

**Issue by wy373226722** [brankosekulic/trimHtml#8]
TypeError: Cannot read property 'replace' of undefined
      at trimHtml (C:\wwwroot\yidata\node_modules\trim-html\index.js:16:19)
      at index.js:43:33
      at _fulfilled (C:\wwwroot\yidata\node_modules\q\q.js:834:54)
      at self.promiseDispatch.done (C:\wwwroot\yidata\node_modules\q\q.js:863:30)
      at Promise.promise.promiseDispatch (C:\wwwroot\yidata\node_modules\q\q.js:796:13)
      at C:\wwwroot\yidata\node_modules\q\q.js:604:44
      at runSingle (C:\wwwroot\yidata\node_modules\q\q.js:137:13)
      at flush (C:\wwwroot\yidata\node_modules\q\q.js:125:13)
      at nextTickCallbackWith0Args (node.js:420:9)
      at process._tickDomainCallback (node.js:390:13)

**Comment by wy373226722** [comment]
My error，sorry。
